config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :shows
  resources :promotions
  devise_for :users
  resources :titles
  resources :wrestlers

  get '/wrestlers' => 'wrestlers#index'
  get '/titles' =>'title#index'
  get '/promotions' =>'promotion#index'
  get '/shows' =>'show#index'
  get '/matches' =>'matches#index'

  root 'wrestlers#index'

end

app/models/wrestler.rb
class Wrestler < ActiveRecord::Base
  has_attached_file :image, styles: {large: "600x600", medium: "300x300", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  belongs_to :title
  belongs_to :match

end

app/controllers/wrestlers_controller.rb
class WrestlersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_wrestler, only: [:show, :edit, :update, :destroy]

  # GET /wrestlers
  # GET /wrestlers.json
  def index
    @wrestlers = Wrestler.all
  end

  # GET /wrestlers/1
  # GET /wrestlers/1.json
  def show
  end

  # GET /wrestlers/new
  def new
    @wrestler = Wrestler.new
  end

  # GET /wrestlers/1/edit
  def edit
  end

  # POST /wrestlers
  # POST /wrestlers.json
  def create
    @wrestler = Wrestler.new(wrestler_params)

    respond_to do |format|
      if @wrestler.save
        format.html { redirect_to @wrestler, notice: 'Wrestler was successfully created.' }
        format.json { render :show, status: :created, location: @wrestler }
      else
        format.html { render :new }
        format.json { render json: @wrestler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wrestlers/1
  # PATCH/PUT /wrestlers/1.json
  def update
    respond_to do |format|
      if @wrestler.update(wrestler_params)
        format.html { redirect_to @wrestler, notice: 'Wrestler was successfully updated.' }
        format.json { render :show, status: :ok, location: @wrestler }
      else
        format.html { render :edit }
        format.json { render json: @wrestler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wrestlers/1
  # DELETE /wrestlers/1.json
  def destroy
    @wrestler.destroy
    respond_to do |format|
      format.html { redirect_to wrestlers_url, notice: 'Wrestler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wrestler
      @wrestler = Wrestler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wrestler_params
      params.require(:wrestler).permit(:real_name, :wrestling_name, :age, :division, :turn, :wage, :image)
    end
end

app/helpers/wrestlers_helper.rb
module WrestlersHelper
end

app/views/wrestlers/_form.html.erb
<%= form_for (@wrestler), html: { multipart: true } do |f| %>
  <% if @wrestler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wrestler.errors.count, "error") %> prohibited this wrestler from being saved:</h2>

      <ul>
      <% @wrestler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :real_name %><br>
    <%= f.text_field :real_name %>
  </div>
  <div class="field">
    <%= f.label :wrestling_name %><br>
    <%= f.text_field :wrestling_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :division %><br>
    <%= f.text_field :division %>
  </div>
  <div class="field">
    <%= f.label :turn %><br>
    <%= f.text_field :turn %>
  </div>
  <div class="field">
    <%= f.label :wage %><br>
    <%= f.text_field :wage %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wrestlers/edit.html.erb
<h1>Editing Wrestler</h1>

<%= render 'form' %>

<%= link_to 'Show', @wrestler %> |
<%= link_to 'Back', wrestlers_path %>

app/views/wrestlers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wrestlers</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Real name</th>
      <th>Wrestling name</th>
      <th>Age</th>
      <th>Division</th>
      <th>Turn</th>
      <th>Wage</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wrestlers.each do |wrestler| %>
      <tr>
        <td><%= image_tag wrestler.image.url(:thumb) %></td>
        <td><%= wrestler.real_name %></td>
        <td><%= wrestler.wrestling_name %></td>
        <td><%= wrestler.age %></td>
        <td><%= wrestler.division %></td>
        <td><%= wrestler.turn %></td>
        <td><%= wrestler.wage %></td>
        <td><%= link_to 'Show', wrestler %></td>
        <td><%= link_to 'Edit', edit_wrestler_path(wrestler) %></td>
        <td><%= link_to 'Destroy', wrestler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wrestler', new_wrestler_path %>

app/views/wrestlers/new.html.erb
<h1>New Wrestler</h1>

<%= render 'form' %>

<%= link_to 'Back', wrestlers_path %>

app/views/wrestlers/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @wrestler.image.url(:thumb) %>

<p>
  <strong>Real name:</strong>
  <%= @wrestler.real_name %>
</p>

<p>
  <strong>Wrestling name:</strong>
  <%= @wrestler.wrestling_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @wrestler.age %>
</p>

<p>
  <strong>Division:</strong>
  <%= @wrestler.division %>
</p>

<p>
  <strong>Turn:</strong>
  <%= @wrestler.turn %>
</p>

<p>
  <strong>Wage:</strong>
  <%= @wrestler.wage %>
</p>


<%= link_to 'Edit', edit_wrestler_path(@wrestler) %> |
<%= link_to 'Back', wrestlers_path %>