config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :shows
  resources :promotions
  devise_for :users
  resources :titles
  resources :wrestlers

  get '/wrestlers' => 'wrestlers#index'
  get '/titles' =>'title#index'
  get '/promotions' =>'promotion#index'
  get '/shows' =>'show#index'
  get '/matches' =>'matches#index'

  root 'wrestlers#index'

end

app/models/title.rb
class Title < ActiveRecord::Base
  has_attached_file :image, styles: {large: "600x600", medium: "300x300", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  has_many :wrestlers
  belongs_to :match

end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_title, only: [:show, :edit, :update, :destroy]

  # GET /titles
  # GET /titles.json
  def index
    @titles = Title.all
  end

  # GET /titles/1
  # GET /titles/1.json
  def show
    @title = Title.find(params[:id])
    #w_id = Title.wrestler_id
    #@wrestler = Wrestler.find(w_id)
  end

  # GET /titles/new
  def new
    @title = Title.new
  end

  # GET /titles/1/edit
  def edit
  end

  # POST /titles
  # POST /titles.json
  def create
    @title = Title.new(title_params)

    respond_to do |format|
      if @title.save
        format.html { redirect_to @title, notice: 'Title was successfully created.' }
        format.json { render :show, status: :created, location: @title }
      else
        format.html { render :new }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titles/1
  # PATCH/PUT /titles/1.json
  def update
    respond_to do |format|
      if @title.update(title_params)
        format.html { redirect_to @title, notice: 'Title was successfully updated.' }
        format.json { render :show, status: :ok, location: @title }
      else
        format.html { render :edit }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1
  # DELETE /titles/1.json
  def destroy
    @title.destroy
    respond_to do |format|
      format.html { redirect_to titles_url, notice: 'Title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_title
      @title = Title.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def title_params
      params.require(:title).permit(:name, :division, :prestige, :image, :wrestler_id)
    end
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/titles/_form.html.erb
<%= form_for (@title), html: { multipart: true } do |f| %>
  <% if @title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
      <% @title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :division %><br>
    <%= f.text_field :division %>
  </div>
  <div class="field">
    <%= f.label :prestige %><br>
    <%= f.text_field :prestige %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label "Champion" %><br>
    <%= f.collection_select(:wrestler_id, Wrestler.all, :id, :wrestling_name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/titles/edit.html.erb
<h1>Editing Title</h1>

<%= render 'form' %>

<%= link_to 'Show', @title %> |
<%= link_to 'Back', titles_path %>

app/views/titles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Titles</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Division</th>
      <th>Prestige</th>
      <th>Wrestler</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @titles.each do |title| %>
      <tr>
        <td><%= image_tag title.image.url(:thumb) %></td>
        <td><%= title.name %></td>
        <td><%= title.division %></td>
        <td><%= title.prestige %></td>
        <td><%= title.wrestlers%></td>


        <td><%= link_to 'Show', title %></td>
        <td><%= link_to 'Edit', edit_title_path(title) %></td>
        <td><%= link_to 'Destroy', title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Title', new_title_path %>

app/views/titles/new.html.erb
<h1>New Title</h1>

<%= render 'form' %>

<%= link_to 'Back', titles_path %>

app/views/titles/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @title.image.url(:thumb) %>
<p>
  <strong>Name:</strong>
  <%= @title.name %>
</p>

<p>
  <strong>Division:</strong>
  <%= @title.division %>
</p>

<p>
  <strong>Prestige:</strong>
  <%= @title.prestige %>
</p>


<p>
  <strong>Wrestler:</strong>
  <%= @wrestler %>
</p>

<%= link_to 'Edit', edit_title_path(@title) %> |
<%= link_to 'Back', titles_path %>