config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :shows
  resources :promotions
  devise_for :users
  resources :titles
  resources :wrestlers

  get '/wrestlers' => 'wrestlers#index'
  get '/titles' =>'title#index'
  get '/promotions' =>'promotion#index'
  get '/shows' =>'show#index'
  get '/matches' =>'matches#index'

  root 'wrestlers#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
  has_many :show
  has_many :wrestler
  has_many :wreslter
  has_many :wrestler
  has_many :title
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:show_id, :match_category, :wrestler_id, :wrestler_id, :title_id, :notes, :wrestler_id)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Show" %><br>
    <%= f.collection_select(:show_id, Show.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :match_category %><br>
    <%= f.text_field :match_category %>
  </div>
  <div class="field">
    <%= f.label "Wrestler 1" %><br>
    <%= f.collection_select(:wrestler_id, Wrestler.all, :id, :wrestling_name) %>
  </div>
  <div class="field">
    <%= f.label "Wrestler 2" %><br>
    <%= f.collection_select(:wrestler_id, Wrestler.all, :id, :wrestling_name) %>
  </div>
  <div class="field">
    <%= f.label "Championship" %><br>
    <%= f.collection_select(:title_id, Title.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label "Winner" %><br>
    <%= f.collection_select(:wrestler_id, Wrestler.all, :id, :wrestling_name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Matches</h1>

<table>
  <thead>
    <tr>
      <th>Show</th>
      <th>Match category</th>
      <th>Wrestler</th>
      <th>Wrestler</th>
      <th>Title</th>
      <th>Notes</th>
      <th>Wrestler</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.show %></td>
        <td><%= match.match_category %></td>
        <td><%= match.wrestler %></td>
        <td><%= match.wrestler %></td>
        <td><%= match.title %></td>
        <td><%= match.notes %></td>
        <td><%= match.wrestler %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Show:</strong>
  <%= @match.show %>
</p>

<p>
  <strong>Match category:</strong>
  <%= @match.match_category %>
</p>

<p>
  <strong>Wrestler:</strong>
  <%= @match.wrestler %>
</p>

<p>
  <strong>Wrestler:</strong>
  <%= @match.wrestler %>
</p>

<p>
  <strong>Title:</strong>
  <%= @match.title %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @match.notes %>
</p>

<p>
  <strong>Wrestler:</strong>
  <%= @match.wrestler %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>