config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :shows
  resources :promotions
  devise_for :users
  resources :titles
  resources :wrestlers

  get '/wrestlers' => 'wrestlers#index'
  get '/titles' =>'title#index'
  get '/promotions' =>'promotion#index'
  get '/shows' =>'show#index'
  get '/matches' =>'matches#index'

  root 'wrestlers#index'

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :show
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :set_promotion, only: [:show, :edit, :update, :destroy]

  # GET /promotions
  # GET /promotions.json
  def index
    @promotions = Promotion.all
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new
  end

  # GET /promotions/1/edit
  def edit
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to @promotion, notice: 'Promotion was successfully created.' }
        format.json { render :show, status: :created, location: @promotion }
      else
        format.html { render :new }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1
  # PATCH/PUT /promotions/1.json
  def update
    respond_to do |format|
      if @promotion.update(promotion_params)
        format.html { redirect_to @promotion, notice: 'Promotion was successfully updated.' }
        format.json { render :show, status: :ok, location: @promotion }
      else
        format.html { render :edit }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion.destroy
    respond_to do |format|
      format.html { redirect_to promotions_url, notice: 'Promotion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promotion
      @promotion = Promotion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promotion_params
      params.require(:promotion).permit(:name, :size, :established, :cash)
    end
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_form.html.erb
<%= form_for(@promotion) do |f| %>
  <% if @promotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
      <% @promotion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :established %><br>
    <%= f.text_field :established %>
  </div>
  <div class="field">
    <%= f.label :cash %><br>
    <%= f.text_field :cash %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promotions/edit.html.erb
<h1>Editing Promotion</h1>

<%= render 'form' %>

<%= link_to 'Show', @promotion %> |
<%= link_to 'Back', promotions_path %>

app/views/promotions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Promotions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Established</th>
      <th>Cash</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promotions.each do |promotion| %>
      <tr>
        <td><%= promotion.name %></td>
        <td><%= promotion.size %></td>
        <td><%= promotion.established %></td>
        <td><%= promotion.cash %></td>
        <td><%= link_to 'Show', promotion %></td>
        <td><%= link_to 'Edit', edit_promotion_path(promotion) %></td>
        <td><%= link_to 'Destroy', promotion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promotion', new_promotion_path %>

app/views/promotions/new.html.erb
<h1>New Promotion</h1>

<%= render 'form' %>

<%= link_to 'Back', promotions_path %>

app/views/promotions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @promotion.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @promotion.size %>
</p>

<p>
  <strong>Established:</strong>
  <%= @promotion.established %>
</p>

<p>
  <strong>Cash:</strong>
  <%= @promotion.cash %>
</p>
<a href="/shows/new">Create Show</a>
<%= link_to 'Edit', edit_promotion_path(@promotion) %> |
<%= link_to 'Back', promotions_path %>